version: '3.7'

services:

  mayaom:
    image: maya-o-m
    container_name: maya-o-m
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3007:3000
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
